// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/golang-acexy/starter-gorm/gormstarter"

const TableNameStudent = "demo_student"

// Student mapped from table <demo_student>
type Student struct {
	ID         int64                 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreateTime gormstarter.Timestamp `gorm:"column:create_time;default:CURRENT_TIMESTAMP" json:"createTime"`
	UpdateTime gormstarter.Timestamp `gorm:"column:update_time;default:CURRENT_TIMESTAMP" json:"updateTime"`
	Name       string                `gorm:"column:name;not null" json:"name"`
	Sex        string                `gorm:"column:sex;not null;default:1" json:"sex"`
	Age        int32                 `gorm:"column:age;not null" json:"age"`
	TeacherID  int64                 `gorm:"column:teacher_id" json:"teacherId"`
}

// TableName Student's table name
func (*Student) TableName() string {
	return TableNameStudent
}
