package template

const NotEditMark = `
// Code generated by github.com/acexy/gen (base on gorm.io/gen). DO NOT EDIT.
`

const Header = NotEditMark + `
package {{.Package}}

import(	
	{{range .ImportPkgPaths}}{{.}}` + "\n" + `{{end}}
)
`
